/**
 * @file Automatically generated by barrelsby.
 */

import * as addressNamets from "./address/Name";
import * as learnfunction_exportsts from "./learn/function_exports";
import * as learnobjects_and_typests from "./learn/objects_and_types";
import * as mathMyMathts from "./math/MyMath";
import * as ptestfunctionsts from "./ptest/functions";
export const address = {
  Name: addressNamets,
};
export const learn = {
  function_exports: learnfunction_exportsts,
  objects_and_types: learnobjects_and_typests,
};
export const math = {
  MyMath: mathMyMathts,
};
export const ptest = {
  functions: ptestfunctionsts,
};
